apiVersion: v1
kind: Pod                                     # Definindo o objeto como Pod
metadata:                                     # Passando metadados
  name: portal-noticias                       
  labels:
    app: portal-noticias
spec:                                         # Especificações
  containers:                                 # Especificações de containers
    - name: portal-noticias-container         # Nome do container
      image: aluracursos/portal-noticias:1    # Imagem do container
      ports:                                  # Container ouvindo na porta
        - containerPort: 80
      envFrom:                                # Passando configmap
        - configMapRef:
            name: portal-configmap