apiVersion: v1
kind: Pod                                   # Tipo do objeto
metadata:                                   # Metadados
  name: sistema-noticias
  labels:
    app: sistema-noticias
spec:                                       # Especificações
  containers:                               # Especificações do container
    - name: sistema-noticias-container      # Nome do container
      image: aluracursos/sistema-noticias:1 # Imagem do container
      ports:                                # Container ouvindo na porta..
        - containerPort: 80
      envFrom:                              # Passando configmap
        - configMapRef:
            name: sistema-configmap