apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-container
          name: primeiro-volume
    - name: nginx2-container
      image: nginx:alpine
      volumeMounts:
        - mountPath: /volume-container
          name: primeiro-volume
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /home/volume
        type: DirectoryOrCreate
