apiVersion: v1
kind: Service                 # Tipo do objeto como Service
metadata:                     # Metadados
  name: svc-portal-noticias
spec:                         # Especificações
  type: NodePort              # Tipo do Service como NodePort (Externo)
  ports:                      # Gerenciando portas
    - port: 80                # Expondo internamente
      nodePort: 30000         # Exponto externamente
  selector:                   # Definindo para quem o service irá encaminhar
    app: portal-noticias